set_property SRC_FILE_INFO {cfile:E:/Diak/GyongyosiRobert/UKDA/LedStripControl/LedStripControl.srcs/constrs_1/new/constraint.xdc rfile:../../../LedStripControl.srcs/constrs_1/new/constraint.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J15 IOSTANDARD LVCMOS33} [get_ports reset]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN L16 IOSTANDARD LVCMOS33} [get_ports start]
